Add the linters
jips-on/Portfolio-Mobile-version pull request #1
Opened 2022-09-23 11:59 UTC by jips-on

Add the linters

2022-09-24 11:34 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @jips-on 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️

## Required Changes:
- [ ] Kindly update the pull request's title to make it descriptive of the work that has been done here 👍 
- [ ] Kindly update the pull request's description. It should include a summary descriptive of all the changes that were made in this branch 👍 

_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 11:34 UTC, ha-manel commented on index.html
> +</div>
- [ ] Kindly replace this `div` tag with `header` tag for semantic reasons 👍

2022-09-24 11:34 UTC, ha-manel commented on index.html
> +    <div>
- [ ] Kindly replace this `div` tag with `section` tag for semantic reasons 💯

2022-09-24 11:34 UTC, ha-manel commented on index.html
> +            </div>
- [ ] It's more semantically correct if the social media icons were a list `ul` where each icon is a list item `li` that has an anchor tag `a` 👍 Kindly replace the div with the previously mentioned structure.
- [ ] Also, kindly try to follow the design provided in Figma for this section, the size, the color, and the spacings are much different.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/192095585-7949a714-d482-4ac7-8992-03cba24f3f25.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/192095600-0156baba-e2d7-4dab-8a46-b91d24c7c8ec.png)

2022-09-24 11:34 UTC, ha-manel commented on index.html
> +            <div class="rectangle7"></div>
- [ ] Kindly remove the background images from HTML and put them in CSS as `background-image` of the section. There is no need to download each shape on its own, you can download the whole picture directly from Figma. Kindly check the instructions in this [video](https://www.loom.com/embed/167236d17f104fc18298c5c9888354c9).

2022-09-24 11:34 UTC, ha-manel commented on index.html
> +    </nav>
- [ ] Kindly try to follow the design provided in Figma as much as possible, this includes `font-family`, `font-size`, `color`, `margins` and `paddings`...

## Your design:
![image](https://user-images.githubusercontent.com/50721479/192095453-f623a769-f862-491d-8bf9-3acddf111435.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/192095461-7fcc3462-2f10-4958-880c-de85cda09f08.png)

2022-09-24 11:34 UTC, ha-manel commented on index.html
> +                <h3>LET'S CONNECT</h3>
- [ ] Kindly try to follow the design provided in Figma as much as possible, this includes font-family, font-size, color, margins and padding...

## Your design:
![image](https://user-images.githubusercontent.com/50721479/192095512-1eceb42e-ffcf-45c0-87cf-6c6ffe57e0be.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/192095519-056d9012-ec9f-4862-a66a-3a63e1bb5b12.png)

2022-09-26 16:16 UTC, Nemwel-Boniface approved these changes
## Hello @jips-on         :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making all the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

- [ ] [OPTIONAL] It would be a good thing if you would make your pull request descriptive. Having it as just "Add the linters" does not help much to tell what changes you made and why you would like to merge them into your main project branch. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 16:16 UTC, Nemwel-Boniface commented on index.html
> +       <h2>My Logo</h2>
- [ ] [OPTIONAL] As many people often use the website logo to help navigate them to the main page of the website, I would strongly advise you to make this a link. You can do so by nesting it as follows ``` <h2><a href="#">My Logo</a></h2>```

2022-09-26 17:30 UTC, merged